FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1
ENV PIP_ROOT_USER_ACTION=ignore
WORKDIR /extensions_backend/
COPY requirements.txt /extensions_backend/requirements.txt
COPY packages/ /extensions_backend/packages
COPY manage.py .
RUN pip install --no-index --find-links=/extensions_backend/packages -r /extensions_backend/requirements.txt
COPY . .
EXPOSE 8005
CMD ["python3","manage.py","runserver", "0:8005"]
CMD ["python3","manage.py","runscript", "services"]